[package]
name = "protocol"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
#cobs = { version = "0.5", default-features = false, features = ["defmt"] }
defmt = "1"
postcard = { version = "1", features = ["use-defmt"] }

# By default, `serde` has the `std` feature enabled, which makes it unsuitable for embedded targets
# disabling default-features fixes this
serde = { version = "1.0.*", default-features = false }
enum-iterator = "2"
