[package]
name = "lily_conductor"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
lilyparse = { path = "../lilyparse" }
protocol = { path = "../protocol" }
string_volume = { path = "../string_volume" }
fraction = "0.15"
serialport = { version = "4", default-features = false }
anyhow = "1"
