[package]
edition = "2024"
name = "guitar-fret"
version = "0.1.0"
authors = ["Jonathan Arweck <Jonarw@users.noreply.github.com>"]
resolver = "2"

[[bin]]
name = "guitar-fret"
test = false
bench = false

[dependencies]
defmt = "1.1"
defmt-rtt = "1.2"
panic-probe = { version = "1.0", features = ["print-defmt"] }

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-io = "0.7"
embedded-io-async = "0.7"
embedded-storage = "0.3.1"
cortex-m-rt = "0.7.3"
static_cell = "2"

embassy-executor = { version = "0.10", features = [
    "platform-cortex-m",
    "executor-thread",
    "defmt",
    "executor-interrupt",
] }
embassy-sync = { version = "0.8" }
embassy-time = { version = "0.5", features = [
    "defmt",
    "defmt-timestamp-uptime",
] }

cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
embassy-stm32 = { version = "0.6", features = [
    "defmt",
    "stm32g030f6",
    "unstable-pac",
    "memory-x",
    "time-driver-tim3",
] }

portable-atomic = { version = "1", default-features = false, features = [
    "unsafe-assume-single-core",
] }
protocol = { path = "../protocol" }

[features]
default = ["fret1"]
fret1 = []
fret2 = []
fret3 = []
fret4 = []
fret5 = []
fret6 = []
fret7 = []
fret8 = []
fret9 = []
fret10 = []
fret11 = []
fret12 = []
fret13 = []

[profile.release]
debug = 2
lto = 'fat'
opt-level = 's'
codegen-units = 1
incremental = false

[profile.dev]
debug = 2
lto = 'fat'
opt-level = "s"
codegen-units = 1
incremental = false
