[default.general]
chip = "STM32G030F6"

[default.rtt]
# Whether or not an RTTUI should be opened after flashing.
enabled = true

[default.gdb]
# Whether or not a GDB server should be opened after flashing.
enabled = false
